# Generated by Django 4.2.7 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_product_options_product_hot_deal_label_and_more'),
        ('clients', '0002_deliveryagent_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priority_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_customers', to='market.categories'),
        ),
    ]
