# Generated by Django 4.2.7 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_categories_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_hot_deal', '-hot_deal_rank', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_deal_rank',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers place hot deals ahead of other hot deals.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
